- name: Build Solution
      run: msbuild "Stealth Remastered.sln"
      
    - name: Upload Finished ASI
      uses: actions/upload-artifact@v4
      with:
        name: Stealth-Final-Build
        path: |
          **/*.asi
          **/*.dll
