name: Build Stealth Remastered (.asi)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Plugin-SDK
      run: |
        git clone https://github.com/DK22Pac/plugin-sdk.git ../plugin-sdk
        # إعداد متغير البيئة الذي يحتاجه المشروع للوصول للمكتبة
        echo "PLUGIN_SDK_DIR=${{ github.workspace }}\..\plugin-sdk" >> $GITHUB_ENV

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      # سنستخدم Win32 كما اتفقنا لأنها القياسية في plugin-sdk
      run: msbuild "Stealth Remastered.sln" /p:Configuration=Release /p:Platform=Win32

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Stealth-Remastered-Final
        path: |
          Release/*.asi
          bin/*.asi
